spring:
  datasource:
    name: test
    url: jdbc:mysql:///test?useUnicode=true&characterEncoding=utf8
    username: username
    password: password
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: tk.mybatis.springboot.model
  mapper-locations: classpath:mapper/*.xml
#mapper:
#  mappers:
#  - cn.mmooo.dao.WorkerMapper
#  not-empty: false
#  identity: MYSQL
pagehelper:
  helperDialect: mysql
logging:
  level:
    root: INFO
    cn.mmooo: debug